import { readFileSync, writeFileSync } from 'node:fs';

const bundles = [
  [['blog-shell.js'], 'page-header.html'],
  [['blog-outline.js', 'blog-custom.js'], 'page-footer.html']
];
for (const [inputs, output] of bundles) {
  const source = inputs.map(input => {
    const script = readFileSync(new URL('./' + input, import.meta.url), 'utf8').replace(/^\uFEFF/, '').trim();
    if (/<\/script/i.test(script)) throw new Error('Script contains an HTML closing-script sequence: ' + input);
    return script;
  }).join('\n\n');
  writeFileSync(new URL('../' + output, import.meta.url),
    '<!-- Generated by scripts/build-footer.mjs; CSS belongs in page-custom.css. -->\n<script>\n' + source + '\n</script>\n');
}
