import { readFileSync, writeFileSync } from 'node:fs';

for (const [input, output] of [['blog-shell.js', 'page-header.html'], ['blog-custom.js', 'page-footer.html']]) {
  const source = readFileSync(new URL('./' + input, import.meta.url), 'utf8').replace(/^\uFEFF/, '').trim();
  if (/<\/script/i.test(source)) throw new Error('Script contains an HTML closing-script sequence.');
  writeFileSync(new URL('../' + output, import.meta.url),
    '<!-- Generated by scripts/build-footer.mjs; CSS belongs in page-custom.css. -->\n<script>\n' + source + '\n</script>\n');
}
